export const Products = [
  {
    id: 1,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 2,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 3,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 4,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 5,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 6,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 7,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 8,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 9,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
  {
    id: 10,
    name: "Candy",
    quantity: 20,
    type: "candy",
    alertQuantity: 3,
    buyingPrice: 10000,
    sellingPrice: 1000,
  },
];
